### ISSUE TITLE
Seul le premier profil de la liste s'ouvre

### ISSUE THREAD

**Issue by Redjam** [LeCoupa/the-family-automation#1]
En fait, la macro n'ouvre que le premier profil de la liste puis continue de tourner sans ouvrir les autres profiles...

Est-ce que ce problème a déjà été remonté ? Aurais-tu une solution ? 

En tout cas merci pour le partage !

**Comment by LeCoupa** [comment]
Cela fonctionne chez moi, essaye de regarder ce qui ne va pas ligne 76 de ton côté.

https://github.com/LeCoupa/the-family-automation/blob/master/webbots/1_linkedin_autovisits.js#L76

**Comment by Redjam** [comment]
Merci pour ta réponse. La macro ne fonctionne toujours pas chez moi et je n'arrive pas à comprendre pourquoi ... J'ai vérifié la ligne 76 et fait également un teste en changeant de sélecteur (j'ai utilisé le titre h4) et toujours le même résultat : le premier profil s'ouvre, ensuite plus rien ... Je suis bien avec Firefox sans plug-in particulier.

**Comment by PierreLvx** [comment]
@Redjam Utiliserais-tu LinkedIn en Francais?

**Comment by Redjam** [comment]
@PierreLvx Tout à fait ! Une solution ? :)

**Comment by PierreLvx** [comment]
L'intuition de @LeCoupa est donc bonne. Entre la version française et anglaise, un petit détail doit changer. Tu peux confirmer : si tu switches en anglais, ca fonctionne correctement?
